apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: github
  labels:
    app: hello-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s-demo
  template:
    metadata:
      labels:
        app: hello-k8s-demo
    spec:
      containers:
      - name: hello-k8s
        image: bigwhite/hello-kubernetes-demo:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
